#162163267 create view and edit user profile
andela/ah-backend-athena pull request #14
Opened 2018-12-07 11:56 UTC by SokoPaulSokool

###what does this PR do?
Adds create view and edit of user profile

##Description of tasks to be completed
writing unit tests for this feature
Have these endpoints working
POST /api/user
PUT /api/user
GET /api/profiles/:username

##How this can be tested manually

Clone the repo,
 Install the requirements with pip install -r requirements.txt
To run tests, run ./manage.py test

Run python manage.py runserver
Test the endpoints in postman

### Profile creation
Profile is created when user signs up

## To test this
Send post request to http://127.0.0.1:8000/api/users/
with body
```{
	"user":{
			"email":"soko@gmail.com",
			"username":"soko",
			"password":"sokosoko"
			}
}
```
Then login that user by sending  a POST request to http://127.0.0.1:8000/api/users/login/
Login data format --> POST /api/users/login/
with body
```{
	"user":{
			"email":"soko@gmail.com",
			"username":"soko",
			"password":"sokosoko"
			}
}
```
get the token returned

then send a GET request to http://127.0.0.1:8000/api/profiles/soko
![image](https://user-images.githubusercontent.com/10868919/49646246-9c732980-fa2f-11e8-852f-0d7ba487a1ce.png)

## Test update profile
Send a PUT request to http://127.0.0.1:8000/api/user/
with body and authentication token
```
{
  "user":{
    "email": "paul@andela.com",
    "bio": "I like to skateboard",
    "image": "https://www.andela.com/paul.jpg"
  }
}
```

2018-12-07 12:00 UTC, Kasulejoseph approved these changes

2018-12-07 12:00 UTC, joshtrigger approved these changes

2018-12-07 14:15 UTC, collin5 requested changes
Have you fixed issues with edit `bio` and `profile_pic`? Also add tests for this.

2018-12-08 05:12 UTC, SokoPaulSokool commented
I have fixed the issues with edit bio and image and added the tests

2018-12-10 14:25 UTC, collin5 approved these changes

2018-12-10 14:25 UTC, merged