#162163266 Enable Social login via Google, Facebook and Twitter
andela/ah-backend-athena pull request #15
Opened 2018-12-07 17:06 UTC by bibangamba

#### What does this PR do?
This pull request enables social login for users on Google, Facebook, and Twitter

#### Description of tasks to be completed?

- install the API libraries for the different platforms
- write 3 View classes for the different ways of social login
- write validation classes to validate the access/id tokens in each social platform case and return the decoded user information
- write serializer classes for each social case so we can save the user into the database if they don't exist and/or return their user information
- add URL patterns for each social login method

#### How should this be tested?
- Copy the Heroku link attached to this PR via Postman. It will not be available if we have more than 3 PRs open (Heroku limits to 5 free apps). In this case, please git pull the branch and test it locally (we have a list of environment variables we use and can share when needed and do not forget to do a migrate if testing locally).

### Google (`/api/users/google/`)
- append `/api/users/google/` to the link above and paste it into Postman
- in the request body, select JSON and add only the `token` in the body
- the following screenshots show how to get the google `token`

1. Navigate to the [OAuth 2.0 Playground](https://developers.google.com/oauthplayground/?code=4/rAA5GhRc2av0H95cbiy0rsw2ay-B-WlT1rongPUz7iNLbcaG5iSb8hPYjxEBdnjr7PIpdeBhhGVXi0UgnqJU2qA&scope=openid%20email%20profile%20https://www.googleapis.com/auth/plus.me%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/plus.profile.agerange.read%20https://www.googleapis.com/auth/plus.profile.language.read
)
2. Click on the gear icon and enter the client id and client secret (these details belong to an app we created)
`client_id = 399794902926-o2j33g8hv0gq1ceq55jq043adhgcucst.apps.googleusercontent.com`
`client_secret = yv6_4HM1bfpusdU2A_BnZiFG`
3. On the left hand-side, select 'Google OAuth2 API v2' and enable all the scopes and click on the `Authorize APIs` button.

![image](https://user-images.githubusercontent.com/5712103/49646531-61bdc100-fa30-11e8-8fa5-03b3703487e9.png)

4. This will take you to an account selection page and you can pick any gmail account to authorize our app to have access to your data. Click on allow.
![image](https://user-images.githubusercontent.com/5712103/49646888-a0a04680-fa31-11e8-804b-55735307c817.png)

5.The above step gives us an authorization token we can give to the google authorization server so it give us the identity token we need to identify our user. Click on `Exchange authorization code for token` button. On the right-hand side, we get the data we are interested in. Especially the `id_token`. Copy this and take it to postman.
![image](https://user-images.githubusercontent.com/5712103/49647020-28865080-fa32-11e8-8d9b-3f9770d4b0ff.png)

6. use the copied id_token to request user access via the google path as shown below. It should return a JWT. This JWT is our proof that we are logged in. We shall prove that by using it to access a protected path i.e. `/api/user/`.

![image](https://user-images.githubusercontent.com/5712103/49647155-9e8ab780-fa32-11e8-90af-755d9f392c4f.png)

7. Accessing the protected path `/api/user/` using the JWT we received in the previous step.
![image](https://user-images.githubusercontent.com/5712103/49647354-44d6bd00-fa33-11e8-80da-26d3795e8d9b.png)

### Facebook (`/api/users/facebook/`)

To get the facebook `access_token` we want to use in postman:

1. Navigate to the [facebook developer page](https://developers.facebook.com/tools/explorer/). You might/will have to login. This is where we shall retrieve our access_token. You have to [create an app](https://developers.facebook.com/apps) to be able to get an access token that points to this app.

![image](https://user-images.githubusercontent.com/5712103/49651865-6c348680-fa41-11e8-95ac-4326a1b72339.png)

2. Copy the access token you get on the resulting page (after creating the app and doing a creat_access_token). Paste into the body request in Postman
![image](https://user-images.githubusercontent.com/5712103/49651979-c897a600-fa41-11e8-9def-7ff213f45fd0.png)

You are returned a JWT (auth_token) which we can use in the `Authorization` header to access protected routes (like we did in the google social auth way).

### Twitter(/api/users/twitter/)
For twitter's case, we need 2 tokens. The `access_token` and the `access_token_secret`. You can get them from twitter's developer [console](https://developer.twitter.com/en/apps/). They require that you be signed in but it also takes a while to get approved as a twitter developer.

1. getting the token associated with the app `ah-backend-athena`
![image](https://user-images.githubusercontent.com/5712103/49659487-6c3e8180-fa55-11e8-8366-2db0dd83b5ca.png)

2. We pass the `access_token` and the `access_token_secret`in the request body as on string: `token`. You can use the returned `jwt_token` to access a protected route e.g. a GET on `/api/user/`

![image](https://user-images.githubusercontent.com/5712103/49659791-14544a80-fa56-11e8-8e4b-01bfdf354415.png)
*changed the return from each social auth to `jwt_token`: `<token>` for clarity

#### What are the relevant pivotal tracker stories?
#162163266

2018-12-08 09:08 UTC, joshtrigger approved these changes
great work Andrew, however, I do not see any tests for all the awesome functionality

2018-12-08 17:54 UTC, KicaRonaldOkello approved these changes

2018-12-10 06:36 UTC, kafuuma reviewed
Hi Andrew
I have tested the social login for twitter, google and facebook. They all Work well, good work
Please go ahead with writing tests as we have agreed

2018-12-11 05:17 UTC, collin5 requested changes
Thanks! Please add tests for this.

2018-12-11 12:44 UTC, collin5 approved these changes

2018-12-11 12:44 UTC, merged