#162163268 Users should be able to create articles
andela/ah-backend-athena pull request #17
Opened 2018-12-13 14:48 UTC by kafuuma

#### What does this PR do?
This PR delivers a feature for users to create, get, edit and delete articles

#### Description of the tasks to be completed?
- A logged in user can create articles
- A logged in user can view all articles
- Only Authors can delete their own articles
- A logged in user can get a list of articles

#### How should this be manually tested?
- Paste URL in Postman
`https://ah-backend-athena-staging-pr-9.herokuapp.com/api/users/`
```
 
```

Screenshots 

#### What are the relevant pivotal tracker stories
[#162163268
](https://www.pivotaltracker.com/story/show/162163268)

2018-12-13 17:28 UTC, SokoPaulSokool approved these changes

2018-12-13 17:38 UTC, joshtrigger approved these changes

2018-12-14 05:04 UTC, KicaRonaldOkello approved these changes

2018-12-14 08:46 UTC, collin5 requested changes
As we had agreed, an article should be able to take multiple images with position.

2018-12-15 18:49 UTC, kafuuma commented
@collin5  I have made the changes 
An article can now have more than one image

2018-12-16 19:39 UTC, Kasulejoseph approved these changes

2018-12-17 11:49 UTC, bibangamba approved these changes
good job, thanks for implementing my small feedback

2018-12-17 19:05 UTC, collin5 approved these changes

2018-12-17 19:05 UTC, merged