Implement threaded comments-162163270
andela/ah-backend-athena pull request #22
Opened 2018-12-15 15:58 UTC by Kasulejoseph

**What does this PR do?**
This pull request enables users to comment on authors' articles

**Description of tasks to be completed?**
- write tests for the feature
- A user can only delete or update his comment 
- Logged in user can view a list of all comments
- Have these endpoints working:
```
POST/GET /api/articles/:slug/comments/ --> create or get comments
POST/GET /api/articles/:slug/comments/:id/ --> create or get replies
PUT/DELETE /api/articles/:slug/comments/:id/ --> edit or delete an comment
```
**How should this be tested manually?**
- Install the requirements with pip install -r requirements.txt
- To run tests, run ./manage.py test
- Run python manage.py runserver

*Test the following endpoints in postman*
1. Create a comment on article --> POST /api/articles/:slug/comments/ 
`comment body`
```
{
    "comment": {
"comment_body": "Hey, nooo"	
}
} 
```
`output`
![screen shot 2018-12-15 at 18 35 31](https://user-images.githubusercontent.com/32167860/50044677-53a71a80-0098-11e9-8457-74aab43dc386.png)
2. get all comments  --> GET /api/articles/:slug/comments/ 
![screen shot 2018-12-15 at 18 39 05](https://user-images.githubusercontent.com/32167860/50044701-bd272900-0098-11e9-9860-ce3245147bdc.png)

3. reply to a comment --> POST /api/articles/:slug/comments/ : id>/
`reply body`
```
{
    "reply": {
"comment_body": "Hey, bro"	
}
}
```
`output`
![screen shot 2018-12-15 at 18 45 50](https://user-images.githubusercontent.com/32167860/50044768-b351f580-0099-11e9-8c5c-87e35fc2979a.png)

4. get replies --> GET /api/articles/:slug/comments/ : id>/
![screen shot 2018-12-15 at 18 50 46](https://user-images.githubusercontent.com/32167860/50044808-64f12680-009a-11e9-9874-723cd13914fd.png)

5. user can only edit his comment
![screen shot 2018-12-15 at 18 54 40](https://user-images.githubusercontent.com/32167860/50044865-e943a980-009a-11e9-8d1f-edfe539962c3.png)

6. test coverage
![screen shot 2018-12-15 at 18 55 30](https://user-images.githubusercontent.com/32167860/50044872-09736880-009b-11e9-9871-d71dac1fc044.png)

**Relevant pivotal tracker stories**
#162163270

2018-12-16 07:45 UTC, kafuuma approved these changes
I tested this
Multithreading works well

2018-12-17 06:30 UTC, bibangamba approved these changes
great work @Kasulejoseph

2018-12-17 11:07 UTC, KicaRonaldOkello approved these changes

2018-12-17 12:22 UTC, collin5 requested changes

2018-12-17 12:22 UTC, collin5 commented on authors/apps/articles/exceptions.py
> +    default_detail = "Failed, comment or article doesnot exist"
Typo, should be "... does not exist"

2018-12-17 12:56 UTC, collin5 approved these changes

2018-12-17 12:56 UTC, merged

2018-12-17 12:57 UTC, Kasulejoseph commented on authors/apps/articles/exceptions.py
> +    default_detail = "Failed, comment or article doesnot exist"
I have implemented the feedback